USE [master]
GO
/****** Object:  Database [DB_Autor_TiendaLibros]    Script Date: 4/2/2026 23:21:00 ******/
CREATE DATABASE [DB_Autor_TiendaLibros]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_Autor_TiendaLibros', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DB_Autor_TiendaLibros.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_Autor_TiendaLibros_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DB_Autor_TiendaLibros_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_Autor_TiendaLibros].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET ARITHABORT OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET  MULTI_USER 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET QUERY_STORE = ON
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [DB_Autor_TiendaLibros]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 4/2/2026 23:21:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AcademicDegrees]    Script Date: 4/2/2026 23:21:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AcademicDegrees](
	[AcademicDegreeID] [int] IDENTITY(1,1) NOT NULL,
	[DegreeName] [nvarchar](max) NOT NULL,
	[SchoolName] [nvarchar](max) NOT NULL,
	[GraduationDate] [datetime2](7) NULL,
	[AuthorID] [int] NOT NULL,
	[AcademicDegreeGUID] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_AcademicDegrees] PRIMARY KEY CLUSTERED 
(
	[AcademicDegreeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Authors]    Script Date: 4/2/2026 23:21:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Authors](
	[AuthorID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](max) NOT NULL,
	[LastName] [nvarchar](max) NOT NULL,
	[BirthDate] [datetime2](7) NULL,
	[AuthorGUID] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Authors] PRIMARY KEY CLUSTERED 
(
	[AuthorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20260301223404_InitialCreate', N'8.0.24')
GO
SET IDENTITY_INSERT [dbo].[Authors] ON 
GO
INSERT [dbo].[Authors] ([AuthorID], [FirstName], [LastName], [BirthDate], [AuthorGUID]) VALUES (1, N'Enzo', N'NB', CAST(N'1998-03-25T02:50:10.1540000' AS DateTime2), N'12baabe0-9d59-431c-b24e-8ac57eb3daa1')
GO
INSERT [dbo].[Authors] ([AuthorID], [FirstName], [LastName], [BirthDate], [AuthorGUID]) VALUES (2, N'Luca', N'RV', CAST(N'2024-01-01T23:01:21.4380000' AS DateTime2), N'25682a7e-e227-4e41-97e6-d93168932f13')
GO
SET IDENTITY_INSERT [dbo].[Authors] OFF
GO
/****** Object:  Index [IX_AcademicDegrees_AuthorID]    Script Date: 4/2/2026 23:21:00 ******/
CREATE NONCLUSTERED INDEX [IX_AcademicDegrees_AuthorID] ON [dbo].[AcademicDegrees]
(
	[AuthorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AcademicDegrees]  WITH CHECK ADD  CONSTRAINT [FK_AcademicDegrees_Authors_AuthorID] FOREIGN KEY([AuthorID])
REFERENCES [dbo].[Authors] ([AuthorID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AcademicDegrees] CHECK CONSTRAINT [FK_AcademicDegrees_Authors_AuthorID]
GO
USE [master]
GO
ALTER DATABASE [DB_Autor_TiendaLibros] SET  READ_WRITE 
GO
