USE [master]
GO
/****** Object:  Database [DB_Libro_TiendaLibros]    Script Date: 4/2/2026 23:24:34 ******/
CREATE DATABASE [DB_Libro_TiendaLibros]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_Libro_TiendaLibros', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DB_Libro_TiendaLibros.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_Libro_TiendaLibros_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DB_Libro_TiendaLibros_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_Libro_TiendaLibros].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET ARITHABORT OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET  MULTI_USER 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET QUERY_STORE = ON
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [DB_Libro_TiendaLibros]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 4/2/2026 23:24:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Books]    Script Date: 4/2/2026 23:24:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Books](
	[BookID] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](max) NOT NULL,
	[PublishedDate] [datetime2](7) NULL,
	[BookAuthorGUID] [nvarchar](max) NULL,
	[BookGUID] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Books] PRIMARY KEY CLUSTERED 
(
	[BookID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20260305001518_InitialCreate', N'8.0.24')
GO
SET IDENTITY_INSERT [dbo].[Books] ON 
GO
INSERT [dbo].[Books] ([BookID], [Title], [PublishedDate], [BookAuthorGUID], [BookGUID]) VALUES (1, N'Las mil y una noches', CAST(N'1901-01-05T01:12:58.6990000' AS DateTime2), NULL, N'30537451-5335-4616-ab93-09757ced7282')
GO
INSERT [dbo].[Books] ([BookID], [Title], [PublishedDate], [BookAuthorGUID], [BookGUID]) VALUES (2, N'El cuento de Luca', CAST(N'2026-01-01T01:12:58.6990000' AS DateTime2), N'25682a7e-e227-4e41-97e6-d93168932f13', N'c5fe7d8f-59d8-4dbd-bbd0-b8d702da3328')
GO
INSERT [dbo].[Books] ([BookID], [Title], [PublishedDate], [BookAuthorGUID], [BookGUID]) VALUES (3, N'Viaje al centro de la tierra', CAST(N'1864-11-25T05:07:09.2630000' AS DateTime2), N'xyz', N'c02a4f85-fd59-4a0e-af06-9716cb34e814')
GO
SET IDENTITY_INSERT [dbo].[Books] OFF
GO
USE [master]
GO
ALTER DATABASE [DB_Libro_TiendaLibros] SET  READ_WRITE 
GO
